In [2]:
import gym
import numpy as np


In [3]:
env = gym.make("FrozenLake-v0")

In [4]:
print(env.observation_space.n)

16


In [6]:
Q = np.zeros([env.observation_space.n, env.action_space.n])

lr = 0.8 # learning rate
y = 0.95 # Decay rate based on distance
num_episodes = 2000

rList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    while j < 99:
        j += 1
        
        a = np.argmax(Q[s,:] + np.random.rand(1, env.action_space.n) * (1./(i+1)))
        s1, r, d, _ = env.step(a)
        
        Q[s, a] = Q[s, a] + lr * (r + y*np.max(Q[s1, :]) - Q[s, a])
        rAll += r
        s = s1
        if d:
            break
    rList.append(rAll)

In [7]:
print("Score over time: " + str(sum(rList)/num_episodes))

Score over time: 0.484


In [8]:
print("Q table values")
print(Q)

Q table values
[[  6.10083194e-04   2.05061224e-03   1.56347986e-01   2.29055400e-03]
 [  5.50946053e-04   3.47179557e-04   1.22802653e-03   1.01351108e-01]
 [  1.41189702e-03   2.42671347e-03   1.48594723e-03   4.01794316e-02]
 [  2.64849567e-04   2.78375040e-07   2.44964651e-04   2.71153869e-02]
 [  3.12108644e-01   2.61967410e-04   1.41482442e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.71436169e-03   8.62195566e-06   1.71748070e-05   4.16112734e-08]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   5.84870540e-01]
 [  0.00000000e+00   7.80054448e-01   0.00000000e+00   0.00000000e+00]
 [  1.92571149e-01   3.29875106e-05   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.12061623e-01   0.00000